export interface Station {
  id: string;
  name: string;
  genre: string;
  description: string;
  streamUrl: string;
  color: string;
  frequency: string;
  initials: string;
}

export const STATIONS: Station[] = [
  {
    id: "rpp",
    name: "RPP Noticias",
    genre: "Noticias",
    description: "La radio de noticias líder del Perú",
    streamUrl: "https://mdstrm.com/audio/5fab3416b5f9ef165cfab6e9/icecast.audio",
    color: "#C8102E",
    frequency: "730 AM",
    initials: "RPP",
  },
  {
    id: "oxigeno",
    name: "Oxígeno",
    genre: "Electrónica",
    description: "La mejor música electrónica y dance",
    streamUrl: "https://mdstrm.com/audio/5fab0687bcd6c2389ee9480c/live.m3u8",
    color: "#0077B6",
    frequency: "102.1 FM",
    initials: "OXI",
  },
  {
    id: "studio92",
    name: "Studio 92",
    genre: "Pop / Rock",
    description: "Los mejores éxitos del pop y rock",
    streamUrl: "https://mdstrm.com/audio/5fada553978fe1080e3ac5ea/icecast.audio",
    color: "#7B2FBE",
    frequency: "92.5 FM",
    initials: "S92",
  },
  {
    id: "lazona",
    name: "La Zona",
    genre: "Urbano",
    description: "Reggaeton y música urbana",
    streamUrl: "https://mdstrm.com/audio/5fada54116646e098d97e6a5/icecast.audio",
    color: "#E65100",
    frequency: "90.5 FM",
    initials: "ZNA",
  },
  {
    id: "corazon",
    name: "Radio Corazón",
    genre: "Romántica",
    description: "La música que llega al corazón",
    streamUrl: "https://mdstrm.com/audio/5fada514fc16c006bd63370f/icecast.audio",
    color: "#C2185B",
    frequency: "94.3 FM",
    initials: "COR",
  },
  {
    id: "lamega",
    name: "La Mega",
    genre: "Salsa / Tropical",
    description: "El sabor tropical del Perú",
    streamUrl: "https://mdstrm.com/audio/5fada56fe4e09508207a7951/icecast.audio",
    color: "#1B7A48",
    frequency: "96.7 FM",
    initials: "MEG",
  },
  {
    id: "toplatino",
    name: "Top Latino",
    genre: "Latino",
    description: "Lo mejor del pop latino",
    streamUrl: "http://online.radiodifusion.net:8020/stream",
    color: "#D4A017",
    frequency: "Online",
    initials: "TL",
  },
  {
    id: "panamericana",
    name: "Panamericana",
    genre: "Rock Retro",
    description: "Rock clásico y retro",
    streamUrl: "https://mdstrm.com/audio/6598b728d982060896866b8a/icecast.audio",
    color: "#1565C0",
    frequency: "Online",
    initials: "PAN",
  },
  {
    id: "poderosa",
    name: "La Poderosa",
    genre: "Variada",
    description: "La radio más poderosa del Perú",
    streamUrl: "http://stream.zeno.fm/8dppgdapxneuv",
    color: "#6A0DAD",
    frequency: "98.2 FM",
    initials: "POD",
  },
  {
    id: "salsamaestra",
    name: "Salsa Maestra",
    genre: "Salsa",
    description: "La salsa que mueve al Perú",
    streamUrl: "https://stream.zeno.fm/c1skkw28pfeuv",
    color: "#B71C1C",
    frequency: "Online",
    initials: "SM",
  },
  {
    id: "ovacion",
    name: "Ovación",
    genre: "Deportes",
    description: "Radio deportiva del Perú",
    streamUrl: "https://5c3fb01839654.streamlock.net:1963/ipradioovacion1/liveovacion1radio/playlist.m3u8",
    color: "#00695C",
    frequency: "620 AM",
    initials: "OVA",
  },
  {
    id: "boleros",
    name: "Boleros",
    genre: "Boleros",
    description: "Boleros inolvidables para tu alma",
    streamUrl: "https://stream.zeno.fm/5t45zksv7mruv",
    color: "#880E4F",
    frequency: "Online",
    initials: "BOL",
  },
  {
    id: "felicidad",
    name: "Felicidad",
    genre: "Pop",
    description: "Música para ser feliz",
    streamUrl: "https://mdstrm.com/audio/5fad731fcf097a068af3c8f7/icecast.audio",
    color: "#F57F17",
    frequency: "88.9 FM",
    initials: "FEL",
  },
  {
    id: "noventera",
    name: "La Noventera",
    genre: "90s",
    description: "Los mejores éxitos de los 90s",
    streamUrl: "https://host.gometri.com/proxy/lanoventera/stream/",
    color: "#1A237E",
    frequency: "Online",
    initials: "90s",
  },
  {
    id: "panamericanaradio",
    name: "Radio Panam.",
    genre: "Variada",
    description: "Radio Panamericana Lima",
    streamUrl: "https://mdstrm.com/audio/6598b62dded1380470f4e539/icecast.audio",
    color: "#33691E",
    frequency: "Online",
    initials: "PNM",
  },
  {
    id: "chocolate",
    name: "Chocolate",
    genre: "Rock / Pop",
    description: "Rock y pop en español",
    streamUrl: "https://stream.zeno.fm/g2w7ukzh64zuv",
    color: "#4E342E",
    frequency: "Online",
    initials: "CHO",
  },
  {
    id: "rockpop",
    name: "Rock & Pop",
    genre: "Rock",
    description: "Rock y pop los clásicos",
    streamUrl: "http://stream.zeno.fm/0k6va3rg8rhvv",
    color: "#212121",
    frequency: "Online",
    initials: "R&P",
  },
  {
    id: "cumbiaemix",
    name: "Cumbia Mix",
    genre: "Cumbia",
    description: "Cumbia peruana lo mejor",
    streamUrl: "https://mdstrm.com/audio/6598b6ab95a235085823b24f/icecast.audio",
    color: "#E91E8C",
    frequency: "Online",
    initials: "CUM",
  },
  {
    id: "salsaperu",
    name: "Salsa Perú",
    genre: "Salsa",
    description: "Pura salsa peruana",
    streamUrl: "https://stream.zeno.fm/f19941g3teruv",
    color: "#FF6F00",
    frequency: "Online",
    initials: "SAL",
  },
];
